import { AlertTriangle, CalendarClock, CheckCircle2, CircleDollarSign, Eye, FileQuestion, Flag, ListChecks, MessageCircleQuestion, ShieldCheck } from "lucide-react";
import type { PremiumFinding, PremiumInsightItem, PremiumReport } from "@/types/audit";

const usd = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value);

function Section({ id, eyebrow, title, description, children }: { id: string; eyebrow: string; title: string; description: string; children: React.ReactNode }) {
  return <section id={id} className="scroll-mt-28 rounded-[2rem] border border-white/[0.07] bg-white/[0.025] p-6 sm:p-10"><p className="text-xs font-black uppercase tracking-[.17em] text-[#73b8ff]">{eyebrow}</p><h2 className="mt-2 text-3xl font-black tracking-[-.035em] text-white sm:text-4xl">{title}</h2><p className="mt-3 max-w-3xl text-base leading-7 text-[#c8d3df]">{description}</p><div className="mt-7">{children}</div></section>;
}

function InsightCards({ items, accent }: { items: PremiumInsightItem[]; accent: "green" | "gold" | "blue" }) {
  const colors = accent === "green" ? "border-[#36d399]/20 bg-[#36d399]/[0.045] text-[#79e6bd]" : accent === "gold" ? "border-[#f4c542]/20 bg-[#f4c542]/[0.045] text-[#f8d96e]" : "border-[#4da3ff]/20 bg-[#4da3ff]/[0.045] text-[#73b8ff]";
  return <div className="grid gap-4 md:grid-cols-2">{items.map((item, index) => <article key={`${item.title}-${index}`} className={`break-inside-avoid rounded-2xl border p-5 sm:p-6 ${colors}`}><h3 className="text-lg font-black text-white">{item.title}</h3><p className="mt-3 text-[15px] leading-7 text-[#dce4ec]">{item.explanation}</p>{item.evidence && <blockquote className="mt-4 border-l-2 border-current pl-4 text-sm italic leading-6 text-[#c8d3df]">&ldquo;{item.evidence}&rdquo;</blockquote>}{item.source_reference && <p className="mt-2 text-xs font-bold text-current">Source: {item.source_reference}</p>}{item.recommended_action && <p className="mt-4 text-sm font-bold leading-6 text-white">Next step: {item.recommended_action}</p>}</article>)}</div>;
}

function FindingCard({ finding }: { finding: PremiumFinding }) {
  const severity = finding.severity === "Critical" ? "border-red-400/25 bg-red-400/[0.045] text-red-300" : finding.severity === "High" ? "border-orange-400/25 bg-orange-400/[0.045] text-orange-300" : finding.severity === "Medium" ? "border-[#f4c542]/25 bg-[#f4c542]/[0.045] text-[#f8d96e]" : "border-[#4da3ff]/20 bg-[#4da3ff]/[0.035] text-[#73b8ff]";
  return <article id={`finding-${finding.id}`} className={`break-inside-avoid rounded-[1.5rem] border p-5 sm:p-7 ${severity}`}>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-current/25 px-3 py-1 text-xs font-black uppercase">{finding.severity}</span><span className="rounded-full border border-white/10 px-3 py-1 text-xs font-bold text-[#dce4ec]">{finding.confidence}% confidence</span><span className="rounded-full border border-white/10 px-3 py-1 text-xs font-bold text-[#dce4ec]">{finding.category}</span></div><h3 className="mt-4 text-2xl font-black tracking-[-.02em] text-white">{finding.title}</h3></div><p className="text-xl font-black text-white">{finding.amount == null ? "Amount not stated" : usd(finding.amount)}</p></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><div><h4 className="text-xs font-black uppercase tracking-[.14em] text-current">Plain-English explanation</h4><p className="mt-2 leading-7 text-[#dce4ec]">{finding.explanation}</p></div><div><h4 className="text-xs font-black uppercase tracking-[.14em] text-current">Why it matters</h4><p className="mt-2 leading-7 text-[#dce4ec]">{finding.whyItMatters}</p></div></div>
    <div className="mt-5 rounded-xl border border-white/[0.08] bg-black/20 p-4"><p className="text-xs font-black uppercase tracking-[.14em] text-[#73b8ff]">Exact evidence - {finding.location}</p><blockquote className="mt-3 text-[15px] italic leading-7 text-white">&ldquo;{finding.evidenceQuote}&rdquo;</blockquote></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-white/[0.07] bg-black/10 p-4"><h4 className="text-xs font-black uppercase tracking-[.14em] text-[#f8d96e]">Possible financial impact</h4><p className="mt-2 leading-7 text-[#dce4ec]">{finding.financialImpact}</p></div><div className="rounded-xl border border-white/[0.07] bg-black/10 p-4"><h4 className="text-xs font-black uppercase tracking-[.14em] text-[#79e6bd]">Recommended action</h4><p className="mt-2 leading-7 text-[#dce4ec]">{finding.recommendedAction}</p></div></div>
    <div className="mt-5 rounded-xl border border-[#4da3ff]/20 bg-[#4da3ff]/[0.04] p-4"><h4 className="text-xs font-black uppercase tracking-[.14em] text-[#73b8ff]">Finding-specific talking point</h4><p className="mt-2 font-semibold leading-7 text-white">{finding.talkingPoint}</p></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h4 className="text-xs font-black uppercase tracking-[.14em] text-[#c8d3df]">Questions to ask</h4><ul className="mt-3 space-y-2">{finding.questionsToAsk.map((item, index) => <li key={index} className="flex gap-2 text-sm leading-6 text-[#dce4ec]"><span className="text-[#f4c542]">{index + 1}.</span>{item}</li>)}</ul></div><div><h4 className="text-xs font-black uppercase tracking-[.14em] text-[#c8d3df]">Negotiability</h4><p className="mt-3 text-sm leading-6 text-[#dce4ec]">{finding.negotiability}</p><h4 className="mt-4 text-xs font-black uppercase tracking-[.14em] text-[#c8d3df]">Better alternative language</h4><p className="mt-2 text-sm italic leading-6 text-white">&ldquo;{finding.betterAlternativeLanguage}&rdquo;</p></div></div>
  </article>;
}

export function PremiumReportSections({ report }: { report: PremiumReport }) {
  const financial = report.financialImpact;
  const metricCards = [["Confirmed charges", usd(financial.confirmedCharges)], ["Monthly recurring", usd(financial.recurringMonthlyExposure)], ["Estimated annual", usd(financial.estimatedAnnualExposure)], ["Full-contract exposure", financial.contractTermExposure == null ? "Not reliably calculable" : usd(financial.contractTermExposure)], ["Possible savings", usd(financial.possibleSavings)]];
  const severityOrder = ["Critical", "High", "Medium", "Low", "Informational"] as const;
  return <>
    <Section id="financial-impact" eyebrow="Financial impact" title="What the document could cost" description="Confirmed charges and estimates remain separate, with the calculation basis shown instead of hiding uncertainty.">
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{metricCards.map(([label, value]) => <div key={label} className="rounded-2xl border border-white/[0.08] bg-[#0b1525] p-5"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#9fb0c3]">{label}</p><p className="mt-3 text-xl font-black leading-7 text-white">{value}</p></div>)}</div><p className="mt-5 rounded-xl border border-white/[0.06] bg-black/10 p-4 text-sm leading-6 text-[#c8d3df]">{financial.explanation}</p>
    </Section>
    <Section id="timeline" eyebrow="Important dates" title="Contract timeline and deadlines" description="Renewal, cancellation, notice, price-change, trial, and other dates appear only when the document analysis returned supporting evidence.">
      {report.timeline.length ? <div className="space-y-4">{report.timeline.map((item, index) => <article key={`${item.event}-${index}`} className="rounded-2xl border border-[#4da3ff]/20 bg-[#4da3ff]/[0.04] p-5 sm:p-6"><div className="flex gap-3"><CalendarClock className="mt-1 h-5 w-5 shrink-0 text-[#73b8ff]" /><div><p className="text-xl font-black text-white">{item.event}</p><p className="mt-1 font-bold text-[#f8d96e]">{item.date}</p><blockquote className="mt-3 text-sm italic leading-6 text-[#dce4ec]">&ldquo;{item.evidence}&rdquo;</blockquote><p className="mt-2 text-xs font-bold text-[#9fb0c3]">{item.location}</p><p className="mt-3 text-sm font-bold text-white">Action: {item.recommendedAction}</p></div></div></article>)}</div> : <div className="rounded-2xl border border-[#f4c542]/20 bg-[#f4c542]/[0.04] p-6"><p className="font-bold text-white">No deadline was returned with enough evidence to mark it verified.</p><p className="mt-2 leading-7 text-[#dce4ec]">Ask the provider to confirm every renewal, cancellation, notice, trial, and price-change date in writing, then calendar the earliest applicable deadline.</p></div>}
    </Section>
    <Section id="prioritized-findings" eyebrow="Evidence-linked findings" title="Prioritized findings" description="Every issue includes the exact quote and location, financial impact, action, questions, negotiability, and better alternative language.">
      {report.findings.length ? <div className="space-y-8">{severityOrder.map((severity) => { const items = report.findings.filter((finding) => finding.severity === severity); return items.length ? <div key={severity}><div className="mb-4 flex items-center gap-3"><Flag className="h-5 w-5 text-[#f4c542]" /><h3 className="text-2xl font-black text-white">{severity}</h3><span className="rounded-full border border-white/10 px-2.5 py-1 text-xs font-bold text-[#c8d3df]">{items.length}</span></div><div className="space-y-4">{items.map((finding) => <FindingCard key={finding.id} finding={finding} />)}</div></div> : null; })}</div> : <div className="rounded-2xl border border-[#36d399]/20 bg-[#36d399]/[0.04] p-6"><CheckCircle2 className="h-7 w-7 text-[#36d399]" /><h3 className="mt-4 text-xl font-black text-white">No major hidden fee was confirmed</h3><p className="mt-2 leading-7 text-[#dce4ec]">This is still a complete Contract Health Report. Use the protections, missing-details, monitoring, question, and renewal checklists below.</p></div>}
    </Section>
    <Section id="protections" eyebrow="Contract health" title="Positive terms and missing protections" description="A good contract should still produce useful guidance: what to preserve, what to request, and what to verify."><div className="mb-8 flex items-center gap-3"><CheckCircle2 className="h-6 w-6 text-[#36d399]" /><h3 className="text-2xl font-black text-white">Positive terms and protections</h3></div><InsightCards items={report.positiveTerms} accent="green" /><div className="mb-8 mt-10 flex items-center gap-3"><FileQuestion className="h-6 w-6 text-[#f4c542]" /><h3 className="text-2xl font-black text-white">What is missing?</h3></div><InsightCards items={report.missingProtections} accent="gold" /></Section>
    <Section id="watch-later" eyebrow="Ongoing monitoring" title="What to watch later" description="Use this checklist for future invoices, renewals, usage limits, late fees, and policy changes."><InsightCards items={report.watchLater} accent="blue" /></Section>
    <Section id="start-here" eyebrow="Ranked action plan" title="Start here" description="Actions are organized by contract stage so the most useful next step is always clear.">
      <div className="grid gap-4 lg:grid-cols-2">{([["Today", report.actionPlan.today], ["Before signing", report.actionPlan.beforeSigning], ["During negotiation", report.actionPlan.duringNegotiation], ["After signing", report.actionPlan.afterSigning], ["Before renewal", report.actionPlan.beforeRenewal]] as const).map(([title, items]) => <div key={title} className="rounded-2xl border border-white/[0.08] bg-[#0b1525] p-5 sm:p-6"><h3 className="flex items-center gap-2 text-lg font-black text-white"><ListChecks className="h-5 w-5 text-[#f4c542]" />{title}</h3><ol className="mt-4 space-y-3">{items.map((item, index) => <li key={index} className="flex gap-3 text-[15px] leading-7 text-[#dce4ec]"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#4da3ff]/10 text-xs font-black text-[#73b8ff]">{index + 1}</span>{item}</li>)}</ol></div>)}</div>
    </Section>
    <Section id="questions-escalation" eyebrow="Provider strategy" title="Questions and escalation guidance" description="Use the exact questions first, then move through the escalation path while keeping a written record."><div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-[#4da3ff]/20 bg-[#4da3ff]/[0.04] p-5 sm:p-6"><h3 className="flex items-center gap-2 text-xl font-black text-white"><MessageCircleQuestion className="h-5 w-5 text-[#73b8ff]" />Provider-specific questions</h3><ol className="mt-5 space-y-3">{report.providerQuestions.map((item, index) => <li key={index} className="flex gap-3 text-sm leading-6 text-[#dce4ec]"><span className="font-black text-[#73b8ff]">{index + 1}.</span>{item}</li>)}</ol></div><div className="rounded-2xl border border-[#f4c542]/20 bg-[#f4c542]/[0.04] p-5 sm:p-6"><h3 className="flex items-center gap-2 text-xl font-black text-white"><AlertTriangle className="h-5 w-5 text-[#f4c542]" />Escalation steps</h3><ol className="mt-5 space-y-3">{report.escalationSteps.map((item, index) => <li key={index} className="flex gap-3 text-sm leading-6 text-[#dce4ec]"><span className="font-black text-[#f8d96e]">{index + 1}.</span>{item}</li>)}</ol></div></div></Section>
    <Section id="methodology" eyebrow="Evidence and reliability" title="Methodology, confidence, and limitations" description="The report distinguishes document-supported facts from estimates, assumptions, and items that require human confirmation."><div className="rounded-2xl border border-[#4da3ff]/20 bg-[#4da3ff]/[0.04] p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#73b8ff]" /><p className="font-black text-white">{report.executiveOverview.confidence}% evidence confidence</p></div><p className="mt-3 text-sm leading-6 text-[#dce4ec]">{report.methodology.coverage}</p></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{[["Limitations", report.methodology.limitations], ["Unreadable or uncertain areas", report.methodology.unreadableAreas], ["Assumptions", report.methodology.assumptions], ["Human confirmation required", report.methodology.humanConfirmation]].map(([title, items]) => <div key={title as string} className="rounded-2xl border border-white/[0.08] bg-[#0b1525] p-5"><h3 className="flex items-center gap-2 font-black text-white"><Eye className="h-4 w-4 text-[#73b8ff]" />{title as string}</h3><ul className="mt-4 space-y-2">{(items as string[]).map((item, index) => <li key={index} className="flex gap-2 text-sm leading-6 text-[#c8d3df]"><span className="text-[#f4c542]">-</span>{item}</li>)}</ul></div>)}</div></Section>
  </>;
}
