import { Nav } from "@/components/layout/Nav";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/layout/Container";

export function Terms() {
  return (
    <div className="min-h-screen bg-midnight-950">
      <Nav />
      <main className="py-16">
        <Container className="max-w-4xl">
          <article className="space-y-8">
            <header className="space-y-4">
              <h1 className="text-4xl font-bold tracking-tight text-white text-glow">
                Terms of Service
              </h1>
              <p className="text-violet-400/70 text-sm">
                Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
              </p>
            </header>

            <section className="space-y-6">
              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">1. Acceptance of Terms</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  By accessing or using HiddenFeeAI ("the Service"), you agree to be bound by these Terms of Service. 
                  If you do not agree to these terms, you may not use the Service.
                </p>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">2. Service Description</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  HiddenFeeAI is an AI-powered document analysis tool that processes uploaded documents to identify potential 
                  hidden fees, billing errors, duplicate charges, and contract risks. The Service uses artificial intelligence 
                  to analyze document text and generate audit reports.
                </p>
                <p className="text-violet-200/80 leading-relaxed">
                  The Service supports PDF, image (PNG, JPG, WEBP, TIFF), DOCX, TXT, CSV, and XLSX file formats. 
                  Documents are temporarily processed and automatically deleted after analysis.
                </p>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">3. User Responsibilities</h2>
                <p className="text-violet-200/80 leading-relaxed">As a user of the Service, you agree to:</p>
                <ul className="list-disc pl-6 space-y-2 text-violet-200/80">
                  <li>Provide accurate information when using the Service</li>
                  <li>Only upload documents you have the legal right to analyze</li>
                  <li>Not upload documents containing malware or malicious content</li>
                  <li>Not attempt to reverse engineer or abuse the Service</li>
                  <li>Comply with all applicable laws and regulations</li>
                </ul>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">4. Acceptable Use</h2>
                <p className="text-violet-200/80 leading-relaxed">You agree not to:</p>
                <ul className="list-disc pl-6 space-y-2 text-violet-200/80">
                  <li>Use the Service for any unlawful purpose</li>
                  <li>Attempt to disrupt or overload the Service infrastructure</li>
                  <li>Upload documents containing viruses, malware, or harmful code</li>
                  <li>Use automated tools to scrape or abuse the Service</li>
                  <li>Misrepresent your identity or affiliation</li>
                </ul>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">5. Intellectual Property</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  The HiddenFeeAI name, logo, brand, and software are proprietary. The Service and its original content, 
                  features, and functionality are owned by HiddenFeeAI and are protected by applicable intellectual property laws.
                </p>
                <p className="text-violet-200/80 leading-relaxed">
                  Audit reports generated by the Service are provided for your personal use. You may download, save, and share 
                  your audit reports as you see fit.
                </p>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">6. AI Limitations</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  HiddenFeeAI uses artificial intelligence to analyze documents. While we strive for accuracy, AI analysis 
                  may occasionally produce incorrect or incomplete results. The Service should be used as a tool to assist 
                  in document review, not as a sole decision-making system.
                </p>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">7. Accuracy Disclaimer</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  HiddenFeeAI provides analysis and identification of potential issues in your documents. However, we do not 
                  guarantee that all hidden fees, billing errors, or contract risks will be detected. The accuracy of the 
                  analysis depends on document quality, formatting, and the complexity of the content. Always review the 
                  original documents and consult appropriate professionals.
                </p>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">8. No Legal or Financial Advice</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  HiddenFeeAI does not provide legal, financial, or accounting advice. The audit reports generated by the 
                  Service are for informational purposes only. You should consult with qualified legal, financial, or 
                  accounting professionals regarding any findings or recommendations. Use of the Service does not create 
                  a professional-client relationship.
                </p>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">9. Payment Terms</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  Certain features of HiddenFeeAI may require payment. Fees will be clearly displayed before you commit 
                  to a purchase. Payments are processed through our third-party payment processor. Refunds are handled 
                  in accordance with our Refund Policy.
                </p>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">10. Limitation of Liability</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  To the maximum extent permitted by law, HiddenFeeAI and its operators shall not be liable for any indirect, 
                  incidental, special, consequential, or punitive damages arising from your use of the Service. This includes 
                  any financial losses, missed savings, or business interruptions resulting from reliance on audit reports.
                </p>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">11. Termination</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  We reserve the right to terminate or suspend access to the Service at our sole discretion, without prior 
                  notice, for conduct that we believe violates these Terms or is harmful to other users, third parties, 
                  or the Service itself.
                </p>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">12. Governing Law</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, 
                  without regard to its conflict of law provisions. Any disputes arising under these Terms shall be 
                  resolved in the courts of Delaware.
                </p>
              </div>

              <div className="glass-panel p-6 rounded-xl space-y-4">
                <h2 className="text-2xl font-bold text-white">13. Contact</h2>
                <p className="text-violet-200/80 leading-relaxed">
                  For questions about these Terms of Service, please contact us at:
                </p>
                <p className="text-violet-400 font-medium">support@hiddenfeehub.com</p>
              </div>
            </section>
          </article>
        </Container>
      </main>
      <Footer />
    </div>
  );
}