import type { Env, ExtractionResult } from "../types.js";
import * as errors from "../utils/errors.js";

/**
 * Layered extraction pipeline for Cloudflare Workers:
 * 1. Native PDF text extraction via lightweight approach
 * 2. Cloudflare AI OCR fallback for scanned/image PDFs
 * 3. Image OCR for direct image uploads
 * 4. DOCX extraction via JSZip XML parsing
 * 5. TXT/CSV direct text extraction
 */

const ACCEPTED_EXTENSIONS = [
  ".pdf", ".png", ".jpg", ".jpeg", ".webp", ".heic", ".tiff", ".tif",
  ".docx", ".doc", ".txt", ".csv", ".xlsx", ".xls", ".xlsm",
];

export function isAcceptedExtension(filename: string): boolean {
  const ext = "." + filename.toLowerCase().split(".").pop();
  return ACCEPTED_EXTENSIONS.includes(ext);
}

export function getExtension(filename: string): string {
  return "." + filename.toLowerCase().split(".").pop();
}

/**
 * Extract text from a PDF by reading raw bytes and looking for text content.
 * This is a lightweight approach that works within Workers' 1MB code limit.
 * It handles native text PDFs by extracting embedded text streams.
 */
async function extractPdfNative(buffer: ArrayBuffer): Promise<string | null> {
  try {
    const bytes = new Uint8Array(buffer);
    const textContent: string[] = [];

    // PDF text objects are typically between BT and ET markers
    // We extract plain text from the raw PDF stream data
    const decoder = new TextDecoder("utf-8");
    let content = decoder.decode(buffer);

    // Try to find and extract text from PDF streams
    // First, try to decompress any FlateDecode streams
    // For simple PDFs, text may be embedded as plain text between parentheses
    
    // Extract text between parentheses in PDF content streams
    // This handles many basic PDFs generated by common tools
    const parenMatches = content.match(/\(([^)]*)\)/g);
    if (parenMatches) {
      for (const match of parenMatches) {
        const text = match.slice(1, -1)
          .replace(/\\n/g, "\n")
          .replace(/\\r/g, "\r")
          .replace(/\\t/g, "\t")
          .replace(/\\([0-7]{3})/g, (_, oct) => String.fromCharCode(parseInt(oct, 8)))
          .replace(/\\(.)/g, "$1")
          .trim();
        if (text.length > 1) {
          textContent.push(text);
        }
      }
    }

    // Also try to extract text from between BT...ET blocks
    const btEtRegex = /BT([\s\S]*?)ET/g;
    let btMatch;
    while ((btMatch = btEtRegex.exec(content)) !== null) {
      const block = btMatch[1];
      // Extract Tj and TJ operator text
      const tjMatches = block.match(/\(([^)]*)\)\s*Tj/g);
      if (tjMatches) {
        for (const tj of tjMatches) {
          const text = tj.match(/\(([^)]*)\)/)?.[1];
          if (text && text.trim().length > 1) {
            textContent.push(text);
          }
        }
      }
    }

    // Also try to decompress and extract - look for common PDF patterns
    // Stream objects may contain compressed text
    const streamMatches = content.match(/stream\s([\s\S]*?)\nendstream/g);
    if (streamMatches) {
      for (const stream of streamMatches) {
        const streamData = stream.replace(/^stream\s/, "").replace(/\nendstream$/, "");
        // Try to detect if it looks like raw text (not compressed)
        if (/^[\x20-\x7E\n\r\t]+$/.test(streamData.substring(0, 100))) {
          textContent.push(streamData.trim());
        }
      }
    }

    const extracted = textContent.join("\n").replace(/\s+/g, " ").trim();
    if (extracted.length > 50) {
      return extracted;
    }

    return null;
  } catch (err) {
    console.log(`[Extractor] Native PDF extraction failed: ${err instanceof Error ? err.message : "Unknown"}`);
    return null;
  }
}

/**
 * OCR via Cloudflare Workers AI for images
 */
async function ocrImage(imageBuffer: ArrayBuffer, env: Env): Promise<string | null> {
  try {
    const base64 = arrayBufferToBase64(imageBuffer);
    const result = await env.AI.run("@cf/unisys/ocr", {
      imageBase64: base64,
    });
    const text = (result as { text?: string }).text ?? "";
    return text.trim().length > 10 ? text.trim() : null;
  } catch (err) {
    console.log(`[Extractor] Cloudflare AI OCR failed: ${err instanceof Error ? err.message : "Unknown"}`);
    return null;
  }
}

/**
 * Extract text from a PDF using Cloudflare AI OCR
 * This handles both native PDFs that failed native extraction and scanned PDFs
 */
async function extractPdfViaOcr(buffer: ArrayBuffer, env: Env): Promise<string | null> {
  try {
    // Try OCR on the entire PDF buffer (works for some PDFs)
    const result = await ocrImage(buffer, env);
    if (result) return result;

    // For multi-page PDFs, we use a simpler approach:
    // Convert first few pages to images and OCR each
    // We use a basic approach - OCR the raw bytes as an image
    // In production, you'd want to use a PDF rendering service
    
    return null;
  } catch {
    return null;
  }
}

// ─── MIME Type Detection ───

function detectMimeType(buffer: ArrayBuffer, fileName: string): string {
  const arr = new Uint8Array(buffer.slice(0, 4));
  if (arr[0] === 0x89 && arr[1] === 0x50 && arr[2] === 0x4E && arr[3] === 0x47) return 'image/png';
  if (arr[0] === 0xFF && arr[1] === 0xD8 && arr[2] === 0xFF) return 'image/jpeg';
  if (arr[0] === 0x52 && arr[1] === 0x49 && arr[2] === 0x46 && arr[3] === 0x46) return 'image/webp';
  
  const ext = fileName.toLowerCase().split('.').pop() ?? '';
  if (ext === 'png') return 'image/png';
  if (ext === 'jpg' || ext === 'jpeg') return 'image/jpeg';
  if (ext === 'webp') return 'image/webp';
  if (ext === 'heic' || ext === 'heif') return 'image/heic';
  if (ext === 'tiff' || ext === 'tif') return 'image/tiff';
  return 'image/png'; // fallback
}

// ─── Gemini Core Services ───

async function extractImageViaGemini(
  base64Image: string,
  mimeType: string,
  env: Env
): Promise<string> {
  const apiKey = env.GEMINI_API_KEY || env.GOOGLE_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY or GOOGLE_API_KEY is not configured");
  }
  const model = env.GEMINI_MODEL || "gemini-1.5-flash";
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [
            {
              inlineData: {
                mimeType: mimeType === 'image/heic' ? 'image/jpeg' : mimeType,
                data: base64Image,
              },
            },
            {
              text: "You are a precise, high-fidelity OCR engine. Extract ALL text from this document image exactly as it appears. Preserve all layout, line breaks, structural elements, and tables as closely as possible. Do not add any conversational text, introductory notes, markdown backticks, or explanation. Return ONLY the raw extracted text.",
            },
          ],
        },
      ],
      safetySettings: [
        { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }
      ]
    }),
  });

  if (!response.ok) {
    const errorText = await response.text().catch(() => "Unknown error");
    throw new Error(`Gemini OCR failed (${response.status}): ${errorText}`);
  }

  const data = await response.json() as any;
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error("Gemini returned empty text or failed to generate content.");
  }

  return text.trim();
}

async function extractPdfViaGemini(
  base64Pdf: string,
  env: Env
): Promise<string> {
  const apiKey = env.GEMINI_API_KEY || env.GOOGLE_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY or GOOGLE_API_KEY is not configured");
  }
  const model = env.GEMINI_MODEL || "gemini-1.5-flash";
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [
            {
              inlineData: {
                mimeType: "application/pdf",
                data: base64Pdf,
              },
            },
            {
              text: "You are a precise, high-fidelity OCR engine. Extract ALL text from this PDF exactly as it appears. Preserve all layout, line breaks, structural elements, and tables as closely as possible. Do not add any conversational text, introductory notes, markdown backticks, or explanation. Return ONLY the raw extracted text.",
            },
          ],
        },
      ],
      safetySettings: [
        { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }
      ]
    }),
  });

  if (!response.ok) {
    const errorText = await response.text().catch(() => "Unknown error");
    throw new Error(`Gemini PDF OCR failed (${response.status}): ${errorText}`);
  }

  const data = await response.json() as any;
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error("Gemini returned empty text or failed to generate content.");
  }

  return text.trim();
}

function arrayBufferToBase64(buffer: ArrayBuffer): string {
  if (typeof globalThis !== 'undefined' && (globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(buffer).toString('base64');
  }
  const bytes = new Uint8Array(buffer);
  let binary = "";
  const chunk = 8192;
  for (let i = 0; i < bytes.length; i += chunk) {
    const slice = bytes.subarray(i, i + chunk);
    binary += String.fromCharCode.apply(null, slice as unknown as number[]);
  }
  return btoa(binary);
}

/**
 * Extract text from TXT files
 */
function extractFromTxt(buffer: ArrayBuffer): ExtractionResult {
  const decoder = new TextDecoder("utf-8");
  const text = decoder.decode(buffer).trim();
  const pages = Math.max(1, Math.ceil(text.length / 2500));
  const lineItems = text.split("\n").filter((l) => l.trim().length > 0).length;
  return {
    text,
    pages,
    lineItems,
    fileType: "txt",
    extractionMethod: "native",
    confidenceScore: 100,
  };
}

/**
 * Extract text from CSV (simple parsing)
 */
function extractFromCsv(buffer: ArrayBuffer): ExtractionResult {
  const decoder = new TextDecoder("utf-8");
  const raw = decoder.decode(buffer);
  const lines = raw.split("\n").filter((l) => l.trim().length > 0);
  const text = lines.join("\n");
  const lineItems = lines.length;
  return {
    text,
    pages: 1,
    lineItems,
    fileType: "spreadsheet",
    extractionMethod: "native",
    confidenceScore: 100,
  };
}

/**
 * Main PDF extraction function with layered pipeline.
 * Priority: native text > OCR fallback
 */
export async function extractPdf(
  buffer: ArrayBuffer,
  env: Env,
  fileName: string = "document.pdf"
): Promise<ExtractionResult> {
  // Phase 1: Native text extraction (lightweight, handles most text-based PDFs)
  const nativeText = await extractPdfNative(buffer);
  if (nativeText) {
    const lineItems = nativeText.split("\n").filter((l) => l.trim().length > 0).length;
    return {
      text: nativeText,
      pages: 1,
      lineItems,
      fileType: "pdf",
      extractionMethod: "native",
      confidenceScore: 90,
    };
  }

  // Phase 2: Try direct Gemini PDF Vision OCR if configured
  const apiKey = env.GEMINI_API_KEY || env.GOOGLE_API_KEY;
  if (apiKey) {
    try {
      console.log(`[Extractor] Attempting direct Gemini PDF Vision OCR for ${fileName}...`);
      const base64 = arrayBufferToBase64(buffer);
      const text = await extractPdfViaGemini(base64, env);
      const lineItems = text.split("\n").filter((l) => l.trim().length > 0).length;
      return {
        text,
        pages: 1,
        lineItems,
        fileType: "pdf",
        extractionMethod: "gemini-pdf-ocr",
        confidenceScore: 95,
      };
    } catch (err) {
      console.error(`[Extractor] Gemini PDF OCR failed, falling back to local OCR:`, err);
    }
  }

  // Phase 3: Cloudflare AI OCR fallback (for scanned/image-based PDFs)
  const ocrText = await extractPdfViaOcr(buffer, env);
  if (ocrText) {
    const lineItems = ocrText.split("\n").filter((l) => l.trim().length > 0).length;
    return {
      text: ocrText,
      pages: 1,
      lineItems,
      fileType: "pdf",
      extractionMethod: "ocr",
      confidenceScore: 75,
    };
  }

  throw errors.badFile("Could not extract text from this PDF. It may be a scanned document or the file may be corrupted. Try uploading a clearer scan or image format (PNG/JPG).");
}

/**
 * Extract text from an image using Cloudflare AI OCR
 */
export async function extractImage(
  buffer: ArrayBuffer,
  env: Env,
  fileName: string = "image.png"
): Promise<ExtractionResult> {
  const apiKey = env.GEMINI_API_KEY || env.GOOGLE_API_KEY;

  if (apiKey) {
    try {
      console.log(`[Extractor] Attempting high-speed Gemini OCR for ${fileName}...`);
      const mimeType = detectMimeType(buffer, fileName);
      const base64 = arrayBufferToBase64(buffer);
      const text = await extractImageViaGemini(base64, mimeType, env);

      const lineItems = text.split("\n").filter((l) => l.trim().length > 0).length;
      return {
        text,
        pages: 1,
        lineItems,
        fileType: "image",
        extractionMethod: "gemini-ocr",
        confidenceScore: 95,
      };
    } catch (err) {
      console.error(`[Extractor] Gemini OCR failed, falling back to local OCR:`, err);
    }
  }

  console.log(`[Extractor] Falling back to local Cloudflare AI OCR for ${fileName}...`);
  const ocrText = await ocrImage(buffer, env);
  if (ocrText) {
    const lineItems = ocrText.split("\n").filter((l) => l.trim().length > 0).length;
    return {
      text: ocrText,
      pages: 1,
      lineItems,
      fileType: "image",
      extractionMethod: "image-ocr",
      confidenceScore: 75,
    };
  }

  throw errors.badFile("Could not extract text from this image. Try a clearer scan or a different format.");
}

/**
 * Extract text from a DOCX using JSZip XML parsing (Workers-compatible).
 */
export async function extractDocx(buffer: ArrayBuffer): Promise<ExtractionResult> {
  try {
    // DOCX is a ZIP file containing XML. We extract text from word/document.xml
    const JSZip = (await import("jszip")).default;
    const zip = await JSZip.loadAsync(buffer);
    const docFile = zip.file("word/document.xml");
    if (!docFile) {
      throw new Error("No document.xml found in DOCX");
    }
    const xmlContent = await docFile.async("text");
    // Simple XML text extraction — strip tags, keep content
    const text = xmlContent
      .replace(/<[^>]*>/g, " ")
      .replace(/&/g, "&")
      .replace(/</g, "<")
      .replace(/>/g, ">")
      .replace(/"/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&#x27;/g, "'")
      .replace(/&#x2019;/g, "'")
      .replace(/&#x2013;/g, "-")
      .replace(/&#x2014;/g, "--")
      .replace(/\s+/g, " ")
      .trim();

    const pages = Math.max(1, Math.ceil(text.length / 2500));
    const lineItems = text.split("\n").filter((l) => l.trim().length > 0).length;
    return { text, pages, lineItems, fileType: "docx", extractionMethod: "native", confidenceScore: 90 };
  } catch (err) {
    console.error("[Extractor] DOCX extraction failed:", err);
    throw errors.badFile("Could not extract text from this DOCX file.");
  }
}

/**
 * Main dispatcher — detect file type and route to the right extractor
 */
export async function extractText(
  buffer: ArrayBuffer,
  fileName: string,
  env: Env
): Promise<ExtractionResult> {
  const ext = getExtension(fileName);

  switch (ext) {
    case ".pdf":
      return extractPdf(buffer, env, fileName);
    case ".png":
    case ".jpg":
    case ".jpeg":
    case ".webp":
    case ".tiff":
    case ".tif":
    case ".heic":
      return extractImage(buffer, env, fileName);
    case ".docx":
    case ".doc":
      return extractDocx(buffer);
    case ".txt":
      return extractFromTxt(buffer);
    case ".csv":
      return extractFromCsv(buffer);
    case ".xlsx":
    case ".xls":
    case ".xlsm":
      // XLSX is a ZIP format — try to extract text from shared strings
      try {
        const JSZip = (await import("jszip")).default;
        const zip = await JSZip.loadAsync(buffer);
        const sharedStrings = zip.file("xl/sharedStrings.xml");
        if (sharedStrings) {
          const xmlContent = await sharedStrings.async("text");
          const text = xmlContent
            .replace(/<[^>]*>/g, " ")
            .replace(/&/g, "&")
            .replace(/</g, "<")
            .replace(/>/g, ">")
            .replace(/"/g, '"')
            .replace(/&#39;/g, "'")
            .replace(/\s+/g, " ")
            .trim();
          if (text.length > 10) {
            const lineItems = text.split("\n").filter((l) => l.trim().length > 0).length;
            return { text, pages: 1, lineItems, fileType: "spreadsheet", extractionMethod: "native", confidenceScore: 85 };
          }
        }
        // Fallback to sheet data
        const sheetFile = zip.file("xl/worksheets/sheet1.xml");
        if (sheetFile) {
          const xmlContent = await sheetFile.async("text");
          const text = xmlContent
            .replace(/<[^>]*>/g, " ")
            .replace(/&/g, "&")
            .replace(/</g, "<")
            .replace(/>/g, ">")
            .replace(/\s+/g, " ")
            .trim();
          if (text.length > 10) {
            const lineItems = text.split("\n").filter((l) => l.trim().length > 0).length;
            return { text, pages: 1, lineItems, fileType: "spreadsheet", extractionMethod: "native", confidenceScore: 80 };
          }
        }
      } catch {
        // fallback to raw text extraction
      }
      return extractFromTxt(buffer);
    default:
      throw errors.unsupportedType(ext);
  }
}