import type { Env, ExtractionResult } from "../types.js";
import * as errors from "../utils/errors.js";

/**
 * Layered extraction pipeline for Cloudflare Workers:
 * 1. Native PDF text extraction via lightweight approach
 * 2. Cloudflare AI OCR fallback for scanned/image PDFs
 * 3. Image OCR for direct image uploads
 * 4. DOCX extraction via JSZip XML parsing
 * 5. TXT/CSV direct text extraction
 */

const ACCEPTED_EXTENSIONS = [
  ".pdf", ".png", ".jpg", ".jpeg", ".webp", ".heic", ".tiff", ".tif",
  ".docx", ".doc", ".txt", ".csv", ".xlsx", ".xls", ".xlsm",
];

export function isAcceptedExtension(filename: string): boolean {
  const ext = "." + filename.toLowerCase().split(".").pop();
  return ACCEPTED_EXTENSIONS.includes(ext);
}

export function getExtension(filename: string): string {
  return "." + filename.toLowerCase().split(".").pop();
}

/**
 * Extract text from a PDF by reading raw bytes and looking for text content.
 * This is a lightweight approach that works within Workers' 1MB code limit.
 * It handles native text PDFs by extracting embedded text streams.
 */
async function extractPdfNative(buffer: ArrayBuffer): Promise<string | null> {
  try {
    const bytes = new Uint8Array(buffer);
    const textContent: string[] = [];

    // PDF text objects are typically between BT and ET markers
    // We extract plain text from the raw PDF stream data
    const decoder = new TextDecoder("utf-8");
    let content = decoder.decode(buffer);

    // Try to find and extract text from PDF streams
    // First, try to decompress any FlateDecode streams
    // For simple PDFs, text may be embedded as plain text between parentheses
    
    // Extract text between parentheses in PDF content streams
    // This handles many basic PDFs generated by common tools
    const parenMatches = content.match(/\(([^)]*)\)/g);
    if (parenMatches) {
      for (const match of parenMatches) {
        const text = match.slice(1, -1)
          .replace(/\\n/g, "\n")
          .replace(/\\r/g, "\r")
          .replace(/\\t/g, "\t")
          .replace(/\\([0-7]{3})/g, (_, oct) => String.fromCharCode(parseInt(oct, 8)))
          .replace(/\\(.)/g, "$1")
          .trim();
        if (text.length > 1) {
          textContent.push(text);
        }
      }
    }

    // Also try to extract text from between BT...ET blocks
    const btEtRegex = /BT([\s\S]*?)ET/g;
    let btMatch;
    while ((btMatch = btEtRegex.exec(content)) !== null) {
      const block = btMatch[1];
      // Extract Tj and TJ operator text
      const tjMatches = block.match(/\(([^)]*)\)\s*Tj/g);
      if (tjMatches) {
        for (const tj of tjMatches) {
          const text = tj.match(/\(([^)]*)\)/)?.[1];
          if (text && text.trim().length > 1) {
            textContent.push(text);
          }
        }
      }
    }

    // Also try to decompress and extract - look for common PDF patterns
    // Stream objects may contain compressed text
    const streamMatches = content.match(/stream\s([\s\S]*?)\nendstream/g);
    if (streamMatches) {
      for (const stream of streamMatches) {
        const streamData = stream.replace(/^stream\s/, "").replace(/\nendstream$/, "");
        // Try to detect if it looks like raw text (not compressed)
        if (/^[\x20-\x7E\n\r\t]+$/.test(streamData.substring(0, 100))) {
          textContent.push(streamData.trim());
        }
      }
    }

    const extracted = textContent.join("\n").replace(/\s+/g, " ").trim();
    if (extracted.length > 50) {
      return extracted;
    }

    return null;
  } catch (err) {
    console.log(`[Extractor] Native PDF extraction failed: ${err instanceof Error ? err.message : "Unknown"}`);
    return null;
  }
}

/**
 * OCR via Cloudflare Workers AI for images
 */
async function ocrImage(imageBuffer: ArrayBuffer, env: Env): Promise<string | null> {
  try {
    const base64 = arrayBufferToBase64(imageBuffer);
    const result = await env.AI.run("@cf/unisys/ocr", {
      imageBase64: base64,
    });
    const text = (result as { text?: string }).text ?? "";
    return text.trim().length > 10 ? text.trim() : null;
  } catch (err) {
    console.log(`[Extractor] Cloudflare AI OCR failed: ${err instanceof Error ? err.message : "Unknown"}`);
    return null;
  }
}

/**
 * Detect actual image format from magic bytes (not filename extension).
 * Returns standard MIME type string or "unknown".
 */
function detectImageFormat(buffer: ArrayBuffer): string {
  const arr = new Uint8Array(buffer.slice(0, 12));

  // JPEG: FF D8 FF
  if (arr[0] === 0xFF && arr[1] === 0xD8 && arr[2] === 0xFF) return 'image/jpeg';
  // PNG: 89 50 4E 47
  if (arr[0] === 0x89 && arr[1] === 0x50 && arr[2] === 0x4E && arr[3] === 0x47) return 'image/png';
  // WEBP: RIFF....WEBP
  if (arr[0] === 0x52 && arr[1] === 0x49 && arr[2] === 0x46 && arr[3] === 0x46) {
    const webpMarker = new TextDecoder().decode(arr.slice(8, 12));
    if (webpMarker === 'WEBP') return 'image/webp';
  }
  // HEIC/HEIF: ftyp box at bytes 4-7: 'ftyp', then brand at 8-11
  if (arr[4] === 0x66 && arr[5] === 0x74 && arr[6] === 0x79 && arr[7] === 0x70) {
    const brand = new TextDecoder().decode(arr.slice(8, 12)).toLowerCase();
    if (brand === 'heic' || brand === 'heif' || brand === 'heix' || brand === 'hevc') return `image/${brand}`;
  }
  // BMP: BM
  if (arr[0] === 0x42 && arr[1] === 0x4D) return 'image/bmp';
  return 'unknown';
}

/**
 * Normalize an image before OCR:
 * - Detect actual format from magic bytes
 * - Convert HEIC/HEIF → JPEG (if runtime supports it)
 * - Apply EXIF orientation correction
 * - Resize oversized images while preserving readability
 * - Re-encode as clean JPEG for OCR processing
 *
 * Returns { buffer, mimeType, width, height, format }
 */
interface NormalizedImage {
  buffer: ArrayBuffer;
  mimeType: string;
  width: number;
  height: number;
  format: string; // original detected format
  normalized: boolean; // true if transformation was applied
}

async function normalizeImage(
  imageBuffer: ArrayBuffer,
  fileName: string,
  auditId: string
): Promise<NormalizedImage> {
  const originalBytes = imageBuffer.byteLength;
  const detectedFormat = detectImageFormat(imageBuffer);
  const originalMime = detectedFormat;

  console.log(`[IMAGE_NORMALIZED] auditId=${auditId} fileName="${fileName}" originalMime=${originalMime} originalBytes=${originalBytes}`);

  // Try to decode the image — createImageBitmap is the only decoder available in Workers
  const blob = new Blob([imageBuffer], { type: detectedFormat });
  let bitmap: ImageBitmap;
  try {
    bitmap = await createImageBitmap(blob);
  } catch (decodeErr) {
    const errMsg = decodeErr instanceof Error ? decodeErr.message : String(decodeErr);

    // HEIC/HEIF: Workers runtime does not support this codec
    if (detectedFormat.startsWith('image/heic') || detectedFormat.startsWith('image/heif')) {
      console.error(`[IMAGE_NORMALIZED] auditId=${auditId} HEIC/HEIF not decodable in Workers runtime: ${errMsg}`);
      // Try passing raw bytes to OCR anyway — some AI models handle HEIC natively
      console.log(`[IMAGE_NORMALIZED] auditId=${auditId} passing raw HEIC bytes to OCR (${originalBytes} bytes)`);
      return {
        buffer: imageBuffer,
        mimeType: detectedFormat,
        width: 0,
        height: 0,
        format: detectedFormat,
        normalized: false,
      };
    }

    console.error(`[IMAGE_NORMALIZED] auditId=${auditId} image decoding failed: ${errMsg}`);
    // Return original — let OCR attempt raw bytes
    return {
      buffer: imageBuffer,
      mimeType: detectedFormat,
      width: 0,
      height: 0,
      format: detectedFormat,
      normalized: false,
    };
  }

  let { width, height } = bitmap;
  console.log(`[IMAGE_NORMALIZED] auditId=${auditId} original dimensions: ${width}x${height}`);

  // ── EXIF Orientation correction ──
  // iPhones tag photos with orientation metadata; we must physically rotate
  // the pixel data since OCR models don't interpret EXIF orientation.
  // We handle this during the canvas draw below.

  // ── Resize if too large for OCR (preserve readability at max 2048 longest edge) ──
  const MAX_DIM = 2048;
  if (width > MAX_DIM || height > MAX_DIM) {
    const ratio = Math.min(MAX_DIM / width, MAX_DIM / height);
    width = Math.round(width * ratio);
    height = Math.round(height * ratio);
    console.log(`[IMAGE_NORMALIZED] auditId=${auditId} resized to: ${width}x${height}`);
  }

  // ── Render to canvas (this applies any natural orientation from the ImageBitmap) ──
  const canvas = new OffscreenCanvas(width, height);
  const ctx = canvas.getContext('2d');
  if (!ctx) {
    console.warn(`[IMAGE_NORMALIZED] auditId=${auditId} OffscreenCanvas unavailable — using raw image`);
    bitmap.close();
    return { buffer: imageBuffer, mimeType: detectedFormat, width: 0, height: 0, format: detectedFormat, normalized: false };
  }

  ctx.drawImage(bitmap, 0, 0, width, height);
  bitmap.close();

  // Convert to JPEG for consistent OCR input
  const normalizedBlob = await canvas.convertToBlob({ type: 'image/jpeg', quality: 0.92 });
  const normalizedBuffer = await normalizedBlob.arrayBuffer();

  console.log(`[IMAGE_NORMALIZED] auditId=${auditId} outputMime=image/jpeg outputBytes=${normalizedBuffer.byteLength} width=${width} height=${height} normalized=true`);

  return {
    buffer: normalizedBuffer,
    mimeType: 'image/jpeg',
    width,
    height,
    format: detectedFormat,
    normalized: true,
  };
}

/**
 * Extract text from a PDF using Cloudflare AI OCR
 * This handles both native PDFs that failed native extraction and scanned PDFs
 */
async function extractPdfViaOcr(buffer: ArrayBuffer, env: Env): Promise<string | null> {
  try {
    // Try OCR on the entire PDF buffer (works for some PDFs)
    const result = await ocrImage(buffer, env);
    if (result) return result;

    // For multi-page PDFs, we use a simpler approach:
    // Convert first few pages to images and OCR each
    // We use a basic approach - OCR the raw bytes as an image
    // In production, you'd want to use a PDF rendering service
    
    return null;
  } catch {
    return null;
  }
}

function arrayBufferToBase64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  let binary = "";
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

/**
 * Extract text from TXT files
 */
function extractFromTxt(buffer: ArrayBuffer): ExtractionResult {
  const decoder = new TextDecoder("utf-8");
  const text = decoder.decode(buffer).trim();
  const pages = Math.max(1, Math.ceil(text.length / 2500));
  const lineItems = text.split("\n").filter((l) => l.trim().length > 0).length;
  return {
    text,
    pages,
    lineItems,
    fileType: "txt",
    extractionMethod: "native",
    confidenceScore: 100,
  };
}

/**
 * Extract text from CSV (simple parsing)
 */
function extractFromCsv(buffer: ArrayBuffer): ExtractionResult {
  const decoder = new TextDecoder("utf-8");
  const raw = decoder.decode(buffer);
  const lines = raw.split("\n").filter((l) => l.trim().length > 0);
  const text = lines.join("\n");
  const lineItems = lines.length;
  return {
    text,
    pages: 1,
    lineItems,
    fileType: "spreadsheet",
    extractionMethod: "native",
    confidenceScore: 100,
  };
}

/**
 * Main PDF extraction function with layered pipeline.
 * Priority: native text > OCR fallback
 */
export async function extractPdf(buffer: ArrayBuffer, env: Env): Promise<ExtractionResult> {
  // Phase 1: Native text extraction (lightweight, handles most text-based PDFs)
  const nativeText = await extractPdfNative(buffer);
  if (nativeText) {
    const lineItems = nativeText.split("\n").filter((l) => l.trim().length > 0).length;
    return {
      text: nativeText,
      pages: 1,
      lineItems,
      fileType: "pdf",
      extractionMethod: "native",
      confidenceScore: 90,
    };
  }

  // Phase 2: Cloudflare AI OCR fallback (for scanned/image-based PDFs)
  const ocrText = await extractPdfViaOcr(buffer, env);
  if (ocrText) {
    const lineItems = ocrText.split("\n").filter((l) => l.trim().length > 0).length;
    return {
      text: ocrText,
      pages: 1,
      lineItems,
      fileType: "pdf",
      extractionMethod: "ocr",
      confidenceScore: 75,
    };
  }

  throw errors.badFile("Could not extract text from this PDF. It may be a scanned document or the file may be corrupted. Try uploading a clearer scan or image format (PNG/JPG).");
}

/**
 * Extract text from an image using Cloudflare AI OCR
 */
export async function extractImage(
  buffer: ArrayBuffer,
  env: Env,
  fileName?: string,
  auditId?: string
): Promise<ExtractionResult> {
  const id = auditId || 'unknown';

  // ── Normalize image (format detection, HEIC→JPEG, EXIF orientation, resize) ──
  const normalized = await normalizeImage(buffer, fileName || 'image', id);
  const ocrBuffer = normalized.buffer;

  console.log(`[DOCLING_STARTED] auditId=${id} mimeType=${normalized.mimeType} bytes=${ocrBuffer.byteLength} normalized=${normalized.normalized}`);

  let ocrText: string | null = null;
  let ocrError: string | null = null;

  try {
    ocrText = await ocrImage(ocrBuffer, env);
  } catch (err) {
    ocrError = err instanceof Error ? err.message : String(err);
    console.error(`[DOCLING_RESPONSE] auditId=${id} OCR error: ${ocrError}`);
  }

  if (ocrText && ocrText.trim().length > 10) {
    const lineItems = ocrText.split("\n").filter((l) => l.trim().length > 0).length;
    const textPreview = ocrText.slice(0, 150).replace(/\n/g, ' ');
    console.log(`[DOCLING_COMPLETE] auditId=${id} textLength=${ocrText.length} pageCount=1 extractedTextPreview="${textPreview}..."`);
    return {
      text: ocrText,
      pages: 1,
      lineItems,
      fileType: "image",
      extractionMethod: "image-ocr",
      confidenceScore: 75,
    };
  }

  // Log the actual OCR failure details before throwing
  const textPreview = (ocrText || '').slice(0, 100);
  console.error(`[DOCLING_COMPLETE] auditId=${id} OCR returned empty or insufficient text. textLength=${ocrText?.length || 0} preview="${textPreview}" error=${ocrError || 'none'}`);
  throw errors.badFile("Could not extract text from this image. Try a clearer scan or a different format.");
}

/**
 * Extract text from a DOCX using JSZip XML parsing (Workers-compatible).
 */
export async function extractDocx(buffer: ArrayBuffer): Promise<ExtractionResult> {
  try {
    // DOCX is a ZIP file containing XML. We extract text from word/document.xml
    const JSZip = (await import("jszip")).default;
    const zip = await JSZip.loadAsync(buffer);
    const docFile = zip.file("word/document.xml");
    if (!docFile) {
      throw new Error("No document.xml found in DOCX");
    }
    const xmlContent = await docFile.async("text");
    // Simple XML text extraction — strip tags, keep content
    const text = xmlContent
      .replace(/<[^>]*>/g, " ")
      .replace(/&/g, "&")
      .replace(/</g, "<")
      .replace(/>/g, ">")
      .replace(/"/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&#x27;/g, "'")
      .replace(/&#x2019;/g, "'")
      .replace(/&#x2013;/g, "-")
      .replace(/&#x2014;/g, "--")
      .replace(/\s+/g, " ")
      .trim();

    const pages = Math.max(1, Math.ceil(text.length / 2500));
    const lineItems = text.split("\n").filter((l) => l.trim().length > 0).length;
    return { text, pages, lineItems, fileType: "docx", extractionMethod: "native", confidenceScore: 90 };
  } catch (err) {
    console.error("[Extractor] DOCX extraction failed:", err);
    throw errors.badFile("Could not extract text from this DOCX file.");
  }
}

/**
 * Main dispatcher — detect file type and route to the right extractor
 */
export async function extractText(
  buffer: ArrayBuffer,
  fileName: string,
  env: Env
): Promise<ExtractionResult> {
  const ext = getExtension(fileName);

  switch (ext) {
    case ".pdf":
      return extractPdf(buffer, env);
    case ".png":
    case ".jpg":
    case ".jpeg":
    case ".webp":
    case ".tiff":
    case ".tif":
    case ".heic":
      return extractImage(buffer, env);
    case ".docx":
    case ".doc":
      return extractDocx(buffer);
    case ".txt":
      return extractFromTxt(buffer);
    case ".csv":
      return extractFromCsv(buffer);
    case ".xlsx":
    case ".xls":
    case ".xlsm":
      // XLSX is a ZIP format — try to extract text from shared strings
      try {
        const JSZip = (await import("jszip")).default;
        const zip = await JSZip.loadAsync(buffer);
        const sharedStrings = zip.file("xl/sharedStrings.xml");
        if (sharedStrings) {
          const xmlContent = await sharedStrings.async("text");
          const text = xmlContent
            .replace(/<[^>]*>/g, " ")
            .replace(/&/g, "&")
            .replace(/</g, "<")
            .replace(/>/g, ">")
            .replace(/"/g, '"')
            .replace(/&#39;/g, "'")
            .replace(/\s+/g, " ")
            .trim();
          if (text.length > 10) {
            const lineItems = text.split("\n").filter((l) => l.trim().length > 0).length;
            return { text, pages: 1, lineItems, fileType: "spreadsheet", extractionMethod: "native", confidenceScore: 85 };
          }
        }
        // Fallback to sheet data
        const sheetFile = zip.file("xl/worksheets/sheet1.xml");
        if (sheetFile) {
          const xmlContent = await sheetFile.async("text");
          const text = xmlContent
            .replace(/<[^>]*>/g, " ")
            .replace(/&/g, "&")
            .replace(/</g, "<")
            .replace(/>/g, ">")
            .replace(/\s+/g, " ")
            .trim();
          if (text.length > 10) {
            const lineItems = text.split("\n").filter((l) => l.trim().length > 0).length;
            return { text, pages: 1, lineItems, fileType: "spreadsheet", extractionMethod: "native", confidenceScore: 80 };
          }
        }
      } catch {
        // fallback to raw text extraction
      }
      return extractFromTxt(buffer);
    default:
      throw errors.unsupportedType(ext);
  }
}