import type { AuditReport, VerifiedFinding } from "../types.js";
import type { EnhancedExecutiveSummary } from "../intelligence/executiveSummary.js";
import type { PrioritizedFinding } from "../intelligence/prioritizationEngine.js";
import type { SavingsEstimate } from "../intelligence/savingsEstimator.js";
import type { TrustScore } from "../trust/trustScore.js";
import type { NegotiationAdvice } from "../intelligence/negotiationEngine.js";
import type { EducationTopic } from "../education/consumerEducation.js";
import type { ActionPlan } from "../intelligence/actionPlanEngine.js";
import type { EvidenceCard } from "../trust/evidenceCards.js";
import type { ComparisonResult } from "../comparison/documentComparator.js";
import type { CustomerValueSummary } from "../intelligence/customerValueSummary.js";
import type { ReportMode } from "../intelligence/reportModes.js";

/**
 * Interactive Report Data Model
 * 
 * Structured JSON for frontend consumption (when interactive UI is built).
 * The existing PDF generator continues to work alongside this.
 * 
 * This is the FULL report data — frontend can render any subset.
 */
export interface InteractiveReport {
  reportId: string;
  generatedAt: string;
  mode: ReportMode;

  // Header
  header: {
    documentType: string;
    reviewDate: string;
    pagesReviewed: number;
    lineItems: number;
    issuer: string;
  };

  // Trust & Risk
  trust: TrustScore | null;
  risk: {
    score: number;
    level: string;
    summary: string;
  };

  // Value summary (top-level)
  value: CustomerValueSummary;

  // Executive summary
  executiveSummary: EnhancedExecutiveSummary | null;

  // Priority-ranked findings
  priorityFindings: PrioritizedFinding[];

  // Evidence cards
  evidenceCards: EvidenceCard[];

  // Financial breakdown
  financial: {
    oneTimeCosts: number;
    recurringMonthly: number;
    recurringAnnual: number;
    totalFirstYear: number;
    potentialSavings: {
      label: string;
      estimates: SavingsEstimate[];
    };
  };

  // Negotiation
  negotiation: Array<{
    title: string;
    advice: NegotiationAdvice;
  }>;

  // Action plan
  actionPlan: ActionPlan | null;

  // Education
  education: EducationTopic[];

  // Comparison (if comparing two docs)
  comparison: ComparisonResult | null;

  // All raw findings (for full detail view)
  allFindings: InteractiveFinding[];

  // Metadata
  metadata: {
    extractionMethod: string;
    extractionConfidence: number;
    analyzersUsed: string[];
    totalProcessingTimeMs: number;
    aiGenerated: boolean;
    disclaimer: string;
  };
}

export interface InteractiveFinding {
  id: string;
  title: string;
  category: string;
  severity: string;
  confidenceScore: number;
  confidenceTier: string;
  amount: number | null;
  page: number | null;
  sectionHeading: string | null;
  evidenceQuote: string;
  evidenceContext: string;
  explanation: string;
  whyItMatters: string;
  recommendedAction: string;
  negotiationMessage: string | null;
  verified: boolean;
  evidenceMatchScore: number;
  sourceAnalyzer: string;
}

const DISCLAIMER = "This report was generated by automated AI analysis and is for educational purposes only. It does not constitute legal, financial, or professional advice. Estimates are based on document analysis and are not guaranteed.";

/**
 * Assemble the complete interactive report from all available intelligence.
 */
export function buildInteractiveReport(params: {
  auditReport: AuditReport;
  mode: ReportMode;
  executiveSummary: EnhancedExecutiveSummary | null;
  prioritizedFindings: PrioritizedFinding[];
  trustScore: TrustScore | null;
  evidenceCards: EvidenceCard[];
  savingsEstimates: SavingsEstimate[];
  negotiationAdviceMap: Map<string, NegotiationAdvice>;
  educationTopics: EducationTopic[];
  actionPlan: ActionPlan | null;
  valueSummary: CustomerValueSummary;
  comparison: ComparisonResult | null;
  extractionMethod?: string;
  extractionConfidence?: number;
  totalProcessingTimeMs?: number;
}): InteractiveReport {
  const { auditReport, mode } = params;

  const findings: InteractiveFinding[] = auditReport.findings.map(f => ({
    id: f.id,
    title: f.title,
    category: f.category,
    severity: f.severity,
    confidenceScore: f.confidence_score,
    confidenceTier: f.confidence_score >= 95 ? 'verified' : f.confidence_score >= 90 ? 'high' : f.confidence_score >= 80 ? 'moderate' : 'low',
    amount: f.amount,
    page: f.page,
    sectionHeading: f.line_reference || null,
    evidenceQuote: f.evidence,
    evidenceContext: '',
    explanation: f.explanation,
    whyItMatters: f.why_it_matters,
    recommendedAction: f.recommended_action,
    negotiationMessage: f.negotiation_message || null,
    verified: true,
    evidenceMatchScore: 0.9,
    sourceAnalyzer: 'v2-pipeline',
  }));

  const negotiationEntries = Array.from(params.negotiationAdviceMap.entries()).map(([id, advice]) => ({
    title: id,
    advice,
  }));

  const totalSavings = params.savingsEstimates.reduce((s, e) => s + e.currentAmount, 0);
  const totalLow = params.savingsEstimates.filter(e => e.estimatable).reduce((s, e) => s + e.rangeLow, 0);
  const totalHigh = params.savingsEstimates.filter(e => e.estimatable).reduce((s, e) => s + e.rangeHigh, 0);

  return {
    reportId: auditReport.document_meta.report_id,
    generatedAt: new Date().toISOString(),
    mode,

    header: {
      documentType: auditReport.document_meta.document_type || 'Document',
      reviewDate: auditReport.document_meta.analysis_date,
      pagesReviewed: auditReport.document_meta.pages_reviewed,
      lineItems: auditReport.document_meta.line_items_reviewed,
      issuer: auditReport.document_meta.issuer || 'Not identified',
    },

    trust: params.trustScore,
    risk: {
      score: auditReport.risk_score,
      level: auditReport.risk_level,
      summary: params.executiveSummary?.riskSummary || '',
    },

    value: params.valueSummary,

    executiveSummary: params.executiveSummary,

    priorityFindings: params.prioritizedFindings,

    evidenceCards: params.evidenceCards,

    financial: {
      oneTimeCosts: params.executiveSummary?.oneTimeCosts || 0,
      recurringMonthly: params.executiveSummary?.recurringMonthly || 0,
      recurringAnnual: params.executiveSummary?.recurringAnnual || 0,
      totalFirstYear: params.executiveSummary?.totalFirstYear || 0,
      potentialSavings: {
        label: totalHigh > 0 ? `$${totalLow} - $${totalHigh} possible savings` : '',
        estimates: params.savingsEstimates,
      },
    },

    negotiation: negotiationEntries,

    actionPlan: params.actionPlan,

    education: params.educationTopics,

    comparison: params.comparison,

    allFindings: findings,

    metadata: {
      extractionMethod: params.extractionMethod || 'docling',
      extractionConfidence: params.extractionConfidence || 0.9,
      analyzersUsed: ['feeDetector', 'clauseAnalyzer', 'riskAnalyzer', 'negotiationAdvisor', 'financialImpact'],
      totalProcessingTimeMs: params.totalProcessingTimeMs || 0,
      aiGenerated: true,
      disclaimer: DISCLAIMER,
    },
  };
}